/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'richard' at '3/10/16 6:15 PM' with Gradle 2.11
 *
 * @author richard, @date 3/10/16 6:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
